2019/09/23 10:50:16 [error] 6#6: *2 directory index of "/var/www/deer.local/public/" is forbidden, client: 172.20.0.1, server: deer.local, request: "GET / HTTP/1.1", host: "localhost"
2019/09/23 10:53:15 [error] 6#6: *1 could not find named location "@server", client: 172.20.0.1, server: deer.local, request: "POST /api/login HTTP/1.1", host: "deer.local"
2019/09/23 10:53:17 [error] 6#6: *2 could not find named location "@server", client: 172.20.0.1, server: deer.local, request: "POST /api/login HTTP/1.1", host: "deer.local"
2019/09/23 10:55:14 [error] 6#6: *3 could not find named location "@server", client: 172.20.0.3, server: deer.local, request: "GET /api/x/-180 HTTP/1.1", host: "deer.local:4200", referrer: "http://deer.local:4200/ru/"
2019/09/23 10:55:17 [error] 6#6: *4 could not find named location "@server", client: 172.20.0.3, server: deer.local, request: "GET /api/language/ru HTTP/1.1", host: "deer.local:4200", referrer: "http://deer.local:4200/ru/"
2019/09/23 10:55:17 [error] 6#6: *5 could not find named location "@server", client: 172.20.0.3, server: deer.local, request: "GET /api/user/notification/state HTTP/1.1", host: "deer.local:4200", referrer: "http://deer.local:4200/ru/"
2019/09/23 10:55:17 [error] 6#6: *6 could not find named location "@server", client: 172.20.0.3, server: deer.local, request: "GET /api/cart/get/ HTTP/1.1", host: "deer.local:4200", referrer: "http://deer.local:4200/ru/"
2019/09/23 10:55:18 [error] 6#6: *7 could not find named location "@server", client: 172.20.0.3, server: deer.local, request: "GET /api/statistic HTTP/1.1", host: "deer.local:4200", referrer: "http://deer.local:4200/ru/"
2019/09/23 10:55:18 [error] 6#6: *8 could not find named location "@server", client: 172.20.0.3, server: deer.local, request: "GET /api/categories/root HTTP/1.1", host: "deer.local:4200", referrer: "http://deer.local:4200/ru/"
2019/09/23 10:55:18 [error] 6#6: *9 could not find named location "@server", client: 172.20.0.3, server: deer.local, request: "GET /api/mainpage/shops HTTP/1.1", host: "deer.local:4200", referrer: "http://deer.local:4200/ru/"
2019/09/23 10:55:18 [error] 6#6: *10 could not find named location "@server", client: 172.20.0.3, server: deer.local, request: "GET /api/categories/root HTTP/1.1", host: "deer.local:4200", referrer: "http://deer.local:4200/ru/"
2019/09/23 10:55:18 [error] 6#6: *11 could not find named location "@server", client: 172.20.0.3, server: deer.local, request: "GET /api/categories HTTP/1.1", host: "deer.local:4200", referrer: "http://deer.local:4200/ru/"
2019/09/23 10:55:18 [error] 6#6: *12 could not find named location "@server", client: 172.20.0.3, server: deer.local, request: "GET /api/currency HTTP/1.1", host: "deer.local:4200", referrer: "http://deer.local:4200/ru/"
2019/09/23 10:55:18 [error] 6#6: *13 could not find named location "@server", client: 172.20.0.3, server: deer.local, request: "GET /api/categories/root HTTP/1.1", host: "deer.local:4200", referrer: "http://deer.local:4200/ru/"
2019/09/23 13:15:08 [error] 6#6: *14 could not find named location "@server", client: 172.20.0.1, server: deer.local, request: "POST /api/login HTTP/1.1", host: "deer.local"
2019/09/23 13:20:54 [error] 6#6: *1 connect() failed (113: No route to host) while connecting to upstream, client: 172.20.0.1, server: deer.local, request: "POST /api/login HTTP/1.1", upstream: "fastcgi://172.20.0.9:9000", host: "deer.local"
2019/09/23 13:22:38 [error] 6#6: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.10, server: deer.local, request: "GET /api/x/-180 HTTP/1.1", upstream: "fastcgi://172.20.0.9:9000", host: "deer.local:4200", referrer: "http://deer.local:4200/ru/"
2019/09/23 13:22:42 [error] 6#6: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.10, server: deer.local, request: "GET /api/language/ru HTTP/1.1", upstream: "fastcgi://172.20.0.9:9000", host: "deer.local:4200", referrer: "http://deer.local:4200/ru/"
2019/09/23 13:22:42 [error] 6#6: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.10, server: deer.local, request: "GET /api/user/notification/state HTTP/1.1", upstream: "fastcgi://172.20.0.9:9000", host: "deer.local:4200", referrer: "http://deer.local:4200/ru/"
2019/09/23 13:22:44 [error] 6#6: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.10, server: deer.local, request: "GET /api/cart/get/ HTTP/1.1", upstream: "fastcgi://172.20.0.9:9000", host: "deer.local:4200", referrer: "http://deer.local:4200/ru/"
2019/09/23 13:22:45 [error] 6#6: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.10, server: deer.local, request: "GET /api/categories/root HTTP/1.1", upstream: "fastcgi://172.20.0.9:9000", host: "deer.local:4200", referrer: "http://deer.local:4200/ru/"
2019/09/23 13:22:45 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.10, server: deer.local, request: "GET /api/mainpage/shops HTTP/1.1", upstream: "fastcgi://172.20.0.9:9000", host: "deer.local:4200", referrer: "http://deer.local:4200/ru/"
2019/09/23 13:22:45 [error] 6#6: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.10, server: deer.local, request: "GET /api/statistic HTTP/1.1", upstream: "fastcgi://172.20.0.9:9000", host: "deer.local:4200", referrer: "http://deer.local:4200/ru/"
2019/09/23 13:22:45 [error] 6#6: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.10, server: deer.local, request: "GET /api/categories HTTP/1.1", upstream: "fastcgi://172.20.0.9:9000", host: "deer.local:4200", referrer: "http://deer.local:4200/ru/"
2019/09/23 13:22:45 [error] 6#6: *18 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.10, server: deer.local, request: "GET /api/categories/root HTTP/1.1", upstream: "fastcgi://172.20.0.9:9000", host: "deer.local:4200", referrer: "http://deer.local:4200/ru/"
2019/09/23 13:22:45 [error] 6#6: *21 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.10, server: deer.local, request: "GET /api/currency HTTP/1.1", upstream: "fastcgi://172.20.0.9:9000", host: "deer.local:4200", referrer: "http://deer.local:4200/ru/"
2019/09/23 13:22:45 [error] 6#6: *22 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.10, server: deer.local, request: "GET /api/categories/root HTTP/1.1", upstream: "fastcgi://172.20.0.9:9000", host: "deer.local:4200", referrer: "http://deer.local:4200/ru/"
2019/09/23 13:24:09 [error] 6#6: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: deer.local, request: "GET /api/shop/template/deer.local HTTP/1.1", upstream: "fastcgi://172.20.0.9:9000", host: "deer.local", referrer: "http://deer.local:5000/"
2019/09/23 13:24:31 [error] 6#6: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: deer.local, request: "GET /api/shop/template/deer.local HTTP/1.1", upstream: "fastcgi://172.20.0.9:9000", host: "deer.local", referrer: "http://deer.local:5000/"
2019/09/23 13:30:01 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: deer.local, request: "POST /api/login HTTP/1.1", upstream: "fastcgi://172.20.0.10:9000", host: "deer.local"
2019/09/23 13:30:03 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: deer.local, request: "POST /api/login HTTP/1.1", upstream: "fastcgi://172.20.0.10:9000", host: "deer.local"
2019/09/23 13:30:05 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: deer.local, request: "POST /api/login HTTP/1.1", upstream: "fastcgi://172.20.0.10:9000", host: "deer.local"
2019/09/23 13:31:15 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: deer.local, request: "POST /api/login HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "deer.local"
2019/09/23 13:32:01 [error] 6#6: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: deer.local, request: "GET /api/shop/template/deer.local HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "deer.local", referrer: "http://deer.local:5000/"
2019/09/23 14:02:16 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: deer.local, request: "POST /api/login HTTP/1.1", upstream: "fastcgi://172.20.0.8:9000", host: "deer.local"
2019/09/23 14:02:17 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: deer.local, request: "POST /api/login HTTP/1.1", upstream: "fastcgi://172.20.0.8:9000", host: "deer.local"
2019/09/23 14:02:18 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: deer.local, request: "POST /api/login HTTP/1.1", upstream: "fastcgi://172.20.0.8:9000", host: "deer.local"
2019/09/23 14:02:19 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: deer.local, request: "POST /api/login HTTP/1.1", upstream: "fastcgi://172.20.0.8:9000", host: "deer.local"
2019/09/23 14:02:19 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: deer.local, request: "POST /api/login HTTP/1.1", upstream: "fastcgi://172.20.0.8:9000", host: "deer.local"
2019/09/23 14:04:33 [error] 6#6: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: deer.local, request: "GET /api/shop/template/deer.local HTTP/1.1", upstream: "fastcgi://172.20.0.8:9000", host: "deer.local", referrer: "http://deer.local:5000/"
